package com.yangnk.entity;

import lombok.AllArgsConstructor;
import lombok.Data;

import java.io.Serializable;

@Data
@AllArgsConstructor
public class Experience implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experience.id
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column experience.status
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table experience
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experience.id
     *
     * @return the value of experience.id
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experience.id
     *
     * @param id the value for experience.id
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column experience.status
     *
     * @return the value of experience.status
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column experience.status
     *
     * @param status the value for experience.status
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    public void setStatus(String status) {
        this.status = status;
    }
}