package com.yangnk.entity;

import lombok.AllArgsConstructor;
import lombok.Data;

import java.io.Serializable;

@Data
@AllArgsConstructor
public class Gpu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpu.id
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gpu.count
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gpu
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpu.id
     *
     * @return the value of gpu.id
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpu.id
     *
     * @param id the value for gpu.id
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gpu.count
     *
     * @return the value of gpu.count
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gpu.count
     *
     * @param count the value for gpu.count
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}