package com.example.quartzdemo.model;

import java.io.Serializable;

public class QrtzLocks implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_locks.SCHED_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_locks.LOCK_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String lockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrtz_locks
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_locks.SCHED_NAME
     *
     * @return the value of qrtz_locks.SCHED_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_locks.SCHED_NAME
     *
     * @param schedName the value for qrtz_locks.SCHED_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_locks.LOCK_NAME
     *
     * @return the value of qrtz_locks.LOCK_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getLockName() {
        return lockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_locks.LOCK_NAME
     *
     * @param lockName the value for qrtz_locks.LOCK_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setLockName(String lockName) {
        this.lockName = lockName;
    }
}