package com.example.quartzdemo.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class QrtzSimpropTriggers implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.SCHED_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.TRIGGER_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String triggerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.TRIGGER_GROUP
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String triggerGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.STR_PROP_1
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String strProp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.STR_PROP_2
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String strProp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.STR_PROP_3
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String strProp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.INT_PROP_1
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private Integer intProp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.INT_PROP_2
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private Integer intProp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.LONG_PROP_1
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private Long longProp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.LONG_PROP_2
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private Long longProp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.DEC_PROP_1
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private BigDecimal decProp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.DEC_PROP_2
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private BigDecimal decProp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.BOOL_PROP_1
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String boolProp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simprop_triggers.BOOL_PROP_2
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String boolProp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simprop_triggers.SCHED_NAME
     *
     * @return the value of qrtz_simprop_triggers.SCHED_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simprop_triggers.SCHED_NAME
     *
     * @param schedName the value for qrtz_simprop_triggers.SCHED_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simprop_triggers.TRIGGER_NAME
     *
     * @return the value of qrtz_simprop_triggers.TRIGGER_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getTriggerName() {
        return triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simprop_triggers.TRIGGER_NAME
     *
     * @param triggerName the value for qrtz_simprop_triggers.TRIGGER_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simprop_triggers.TRIGGER_GROUP
     *
     * @return the value of qrtz_simprop_triggers.TRIGGER_GROUP
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getTriggerGroup() {
        return triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simprop_triggers.TRIGGER_GROUP
     *
     * @param triggerGroup the value for qrtz_simprop_triggers.TRIGGER_GROUP
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simprop_triggers.STR_PROP_1
     *
     * @return the value of qrtz_simprop_triggers.STR_PROP_1
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getStrProp1() {
        return strProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simprop_triggers.STR_PROP_1
     *
     * @param strProp1 the value for qrtz_simprop_triggers.STR_PROP_1
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setStrProp1(String strProp1) {
        this.strProp1 = strProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simprop_triggers.STR_PROP_2
     *
     * @return the value of qrtz_simprop_triggers.STR_PROP_2
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getStrProp2() {
        return strProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simprop_triggers.STR_PROP_2
     *
     * @param strProp2 the value for qrtz_simprop_triggers.STR_PROP_2
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setStrProp2(String strProp2) {
        this.strProp2 = strProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simprop_triggers.STR_PROP_3
     *
     * @return the value of qrtz_simprop_triggers.STR_PROP_3
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getStrProp3() {
        return strProp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simprop_triggers.STR_PROP_3
     *
     * @param strProp3 the value for qrtz_simprop_triggers.STR_PROP_3
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setStrProp3(String strProp3) {
        this.strProp3 = strProp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simprop_triggers.INT_PROP_1
     *
     * @return the value of qrtz_simprop_triggers.INT_PROP_1
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public Integer getIntProp1() {
        return intProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simprop_triggers.INT_PROP_1
     *
     * @param intProp1 the value for qrtz_simprop_triggers.INT_PROP_1
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setIntProp1(Integer intProp1) {
        this.intProp1 = intProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simprop_triggers.INT_PROP_2
     *
     * @return the value of qrtz_simprop_triggers.INT_PROP_2
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public Integer getIntProp2() {
        return intProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simprop_triggers.INT_PROP_2
     *
     * @param intProp2 the value for qrtz_simprop_triggers.INT_PROP_2
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setIntProp2(Integer intProp2) {
        this.intProp2 = intProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simprop_triggers.LONG_PROP_1
     *
     * @return the value of qrtz_simprop_triggers.LONG_PROP_1
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public Long getLongProp1() {
        return longProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simprop_triggers.LONG_PROP_1
     *
     * @param longProp1 the value for qrtz_simprop_triggers.LONG_PROP_1
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setLongProp1(Long longProp1) {
        this.longProp1 = longProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simprop_triggers.LONG_PROP_2
     *
     * @return the value of qrtz_simprop_triggers.LONG_PROP_2
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public Long getLongProp2() {
        return longProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simprop_triggers.LONG_PROP_2
     *
     * @param longProp2 the value for qrtz_simprop_triggers.LONG_PROP_2
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setLongProp2(Long longProp2) {
        this.longProp2 = longProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simprop_triggers.DEC_PROP_1
     *
     * @return the value of qrtz_simprop_triggers.DEC_PROP_1
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public BigDecimal getDecProp1() {
        return decProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simprop_triggers.DEC_PROP_1
     *
     * @param decProp1 the value for qrtz_simprop_triggers.DEC_PROP_1
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setDecProp1(BigDecimal decProp1) {
        this.decProp1 = decProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simprop_triggers.DEC_PROP_2
     *
     * @return the value of qrtz_simprop_triggers.DEC_PROP_2
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public BigDecimal getDecProp2() {
        return decProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simprop_triggers.DEC_PROP_2
     *
     * @param decProp2 the value for qrtz_simprop_triggers.DEC_PROP_2
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setDecProp2(BigDecimal decProp2) {
        this.decProp2 = decProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simprop_triggers.BOOL_PROP_1
     *
     * @return the value of qrtz_simprop_triggers.BOOL_PROP_1
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getBoolProp1() {
        return boolProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simprop_triggers.BOOL_PROP_1
     *
     * @param boolProp1 the value for qrtz_simprop_triggers.BOOL_PROP_1
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setBoolProp1(String boolProp1) {
        this.boolProp1 = boolProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simprop_triggers.BOOL_PROP_2
     *
     * @return the value of qrtz_simprop_triggers.BOOL_PROP_2
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getBoolProp2() {
        return boolProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simprop_triggers.BOOL_PROP_2
     *
     * @param boolProp2 the value for qrtz_simprop_triggers.BOOL_PROP_2
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setBoolProp2(String boolProp2) {
        this.boolProp2 = boolProp2;
    }
}