package com.example.quartzdemo.model;

import java.io.Serializable;

public class QrtzSchedulerState implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.SCHED_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.INSTANCE_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String instanceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private Long lastCheckinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private Long checkinInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_scheduler_state.SCHED_NAME
     *
     * @return the value of qrtz_scheduler_state.SCHED_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_scheduler_state.SCHED_NAME
     *
     * @param schedName the value for qrtz_scheduler_state.SCHED_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_scheduler_state.INSTANCE_NAME
     *
     * @return the value of qrtz_scheduler_state.INSTANCE_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getInstanceName() {
        return instanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_scheduler_state.INSTANCE_NAME
     *
     * @param instanceName the value for qrtz_scheduler_state.INSTANCE_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @return the value of qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public Long getLastCheckinTime() {
        return lastCheckinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @param lastCheckinTime the value for qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setLastCheckinTime(Long lastCheckinTime) {
        this.lastCheckinTime = lastCheckinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @return the value of qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public Long getCheckinInterval() {
        return checkinInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @param checkinInterval the value for qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setCheckinInterval(Long checkinInterval) {
        this.checkinInterval = checkinInterval;
    }
}