package com.example.quartzdemo.model;

import java.io.Serializable;

public class QrtzPausedTriggerGrps implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_paused_trigger_grps.SCHED_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_paused_trigger_grps.TRIGGER_GROUP
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String triggerGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_paused_trigger_grps.SCHED_NAME
     *
     * @return the value of qrtz_paused_trigger_grps.SCHED_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_paused_trigger_grps.SCHED_NAME
     *
     * @param schedName the value for qrtz_paused_trigger_grps.SCHED_NAME
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_paused_trigger_grps.TRIGGER_GROUP
     *
     * @return the value of qrtz_paused_trigger_grps.TRIGGER_GROUP
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getTriggerGroup() {
        return triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_paused_trigger_grps.TRIGGER_GROUP
     *
     * @param triggerGroup the value for qrtz_paused_trigger_grps.TRIGGER_GROUP
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }
}