package com.example.quartzdemo.model;

import java.io.Serializable;

public class TScheduleTrigger implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_trigger.id
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_trigger.cron
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String cron;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_trigger.status
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_trigger.job_name
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_schedule_trigger.job_group
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private String jobGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_schedule_trigger
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_trigger.id
     *
     * @return the value of t_schedule_trigger.id
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_trigger.id
     *
     * @param id the value for t_schedule_trigger.id
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_trigger.cron
     *
     * @return the value of t_schedule_trigger.cron
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getCron() {
        return cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_trigger.cron
     *
     * @param cron the value for t_schedule_trigger.cron
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setCron(String cron) {
        this.cron = cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_trigger.status
     *
     * @return the value of t_schedule_trigger.status
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_trigger.status
     *
     * @param status the value for t_schedule_trigger.status
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_trigger.job_name
     *
     * @return the value of t_schedule_trigger.job_name
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_trigger.job_name
     *
     * @param jobName the value for t_schedule_trigger.job_name
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_schedule_trigger.job_group
     *
     * @return the value of t_schedule_trigger.job_group
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_schedule_trigger.job_group
     *
     * @param jobGroup the value for t_schedule_trigger.job_group
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup;
    }
}