package com.yangnk.redisDemo.dao;

import com.yangnk.redisDemo.entity.Network;
import com.yangnk.redisDemo.entity.NetworkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NetworkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    int countByExample(NetworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    int deleteByExample(NetworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    int insert(Network record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    int insertSelective(Network record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    List<Network> selectByExample(NetworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    Network selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    int updateByExampleSelective(@Param("record") Network record, @Param("example") NetworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    int updateByExample(@Param("record") Network record, @Param("example") NetworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    int updateByPrimaryKeySelective(Network record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table network
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    int updateByPrimaryKey(Network record);
}