package com.yangnk.dao;

import com.yangnk.entity.Experience;
import com.yangnk.entity.ExperienceExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

public interface ExperienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    int countByExample(ExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    int deleteByExample(ExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    int insert(Experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    int insertSelective(Experience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    List<Experience> selectByExample(ExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    int updateByExampleSelective(@Param("record") Experience record, @Param("example") ExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table experience
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    int updateByExample(@Param("record") Experience record, @Param("example") ExperienceExample example);

    /**
     * 根据试验id删除试验信息
     * @param id
     */
    void deleteById(@Param("id") int id);
}