package com.yangnk.dao;

import com.yangnk.entity.Gpu;
import com.yangnk.entity.GpuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GpuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpu
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    int countByExample(GpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpu
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    int deleteByExample(GpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpu
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    int insert(Gpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpu
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    int insertSelective(Gpu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpu
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    List<Gpu> selectByExample(GpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpu
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    int updateByExampleSelective(@Param("record") Gpu record, @Param("example") GpuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gpu
     *
     * @mbggenerated Thu May 04 23:40:13 CST 2023
     */
    int updateByExample(@Param("record") Gpu record, @Param("example") GpuExample example);
}