package com.example.quartzdemo.mapper;

import com.example.quartzdemo.model.QrtzBlobTriggers;
import com.example.quartzdemo.model.QrtzBlobTriggersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzBlobTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated Tue Aug 22 11:30:19 CST 2023
     */
    int countByExample(QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated Tue Aug 22 11:30:19 CST 2023
     */
    int deleteByExample(QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated Tue Aug 22 11:30:19 CST 2023
     */
    int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("triggerName") String triggerName, @Param("triggerGroup") String triggerGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated Tue Aug 22 11:30:19 CST 2023
     */
    int insert(QrtzBlobTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated Tue Aug 22 11:30:19 CST 2023
     */
    int insertSelective(QrtzBlobTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated Tue Aug 22 11:30:19 CST 2023
     */
    List<QrtzBlobTriggers> selectByExampleWithBLOBs(QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated Tue Aug 22 11:30:19 CST 2023
     */
    List<QrtzBlobTriggers> selectByExample(QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated Tue Aug 22 11:30:19 CST 2023
     */
    QrtzBlobTriggers selectByPrimaryKey(@Param("schedName") String schedName, @Param("triggerName") String triggerName, @Param("triggerGroup") String triggerGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated Tue Aug 22 11:30:19 CST 2023
     */
    int updateByExampleSelective(@Param("record") QrtzBlobTriggers record, @Param("example") QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated Tue Aug 22 11:30:19 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") QrtzBlobTriggers record, @Param("example") QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated Tue Aug 22 11:30:19 CST 2023
     */
    int updateByExample(@Param("record") QrtzBlobTriggers record, @Param("example") QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated Tue Aug 22 11:30:19 CST 2023
     */
    int updateByPrimaryKeySelective(QrtzBlobTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated Tue Aug 22 11:30:19 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(QrtzBlobTriggers record);
}