package com.example.quartzdemo.mapper;

import com.example.quartzdemo.model.QrtzJobDetails;
import com.example.quartzdemo.model.QrtzJobDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzJobDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int countByExample(QrtzJobDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int deleteByExample(QrtzJobDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("jobName") String jobName, @Param("jobGroup") String jobGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int insert(QrtzJobDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int insertSelective(QrtzJobDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    List<QrtzJobDetails> selectByExampleWithBLOBs(QrtzJobDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    List<QrtzJobDetails> selectByExample(QrtzJobDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    QrtzJobDetails selectByPrimaryKey(@Param("schedName") String schedName, @Param("jobName") String jobName, @Param("jobGroup") String jobGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int updateByExampleSelective(@Param("record") QrtzJobDetails record, @Param("example") QrtzJobDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") QrtzJobDetails record, @Param("example") QrtzJobDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int updateByExample(@Param("record") QrtzJobDetails record, @Param("example") QrtzJobDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int updateByPrimaryKeySelective(QrtzJobDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(QrtzJobDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int updateByPrimaryKey(QrtzJobDetails record);
}