package com.example.quartzdemo.mapper;

import com.example.quartzdemo.model.QrtzLocks;
import com.example.quartzdemo.model.QrtzLocksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzLocksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int countByExample(QrtzLocksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int deleteByExample(QrtzLocksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("lockName") String lockName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int insert(QrtzLocks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int insertSelective(QrtzLocks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    List<QrtzLocks> selectByExample(QrtzLocksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int updateByExampleSelective(@Param("record") QrtzLocks record, @Param("example") QrtzLocksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated Tue Aug 22 11:34:05 CST 2023
     */
    int updateByExample(@Param("record") QrtzLocks record, @Param("example") QrtzLocksExample example);
}