package com.yangnk.mysqldemo.dao;

import com.yangnk.mysqldemo.entity.User1;
import com.yangnk.mysqldemo.entity.User1Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

//@Repository
public interface User1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Wed Mar 22 20:40:58 CST 2023
     */
    int countByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Wed Mar 22 20:40:58 CST 2023
     */
    int deleteByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Wed Mar 22 20:40:58 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Wed Mar 22 20:40:58 CST 2023
     */
    int insert(User1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Wed Mar 22 20:40:58 CST 2023
     */
    int insertSelective(User1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Wed Mar 22 20:40:58 CST 2023
     */
    List<User1> selectByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Wed Mar 22 20:40:58 CST 2023
     */
    User1 selectByPrimaryKey(Integer id);


    String selectUserNameById(@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Wed Mar 22 20:40:58 CST 2023
     */
    int updateByExampleSelective(@Param("record") User1 record, @Param("example") User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Wed Mar 22 20:40:58 CST 2023
     */
    int updateByExample(@Param("record") User1 record, @Param("example") User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Wed Mar 22 20:40:58 CST 2023
     */
    int updateByPrimaryKeySelective(User1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Wed Mar 22 20:40:58 CST 2023
     */
    int updateByPrimaryKey(User1 record);
}