package com.yangnk.hfn.entity;

import java.io.Serializable;

public class TImage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.id
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.imageName
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    private String imagename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.imageAliasName
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    private String imagealiasname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.imageInfo
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    private String imageinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_image
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.id
     *
     * @return the value of t_image.id
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.id
     *
     * @param id the value for t_image.id
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.imageName
     *
     * @return the value of t_image.imageName
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    public String getImagename() {
        return imagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.imageName
     *
     * @param imagename the value for t_image.imageName
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    public void setImagename(String imagename) {
        this.imagename = imagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.imageAliasName
     *
     * @return the value of t_image.imageAliasName
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    public String getImagealiasname() {
        return imagealiasname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.imageAliasName
     *
     * @param imagealiasname the value for t_image.imageAliasName
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    public void setImagealiasname(String imagealiasname) {
        this.imagealiasname = imagealiasname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.imageInfo
     *
     * @return the value of t_image.imageInfo
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    public String getImageinfo() {
        return imageinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.imageInfo
     *
     * @param imageinfo the value for t_image.imageInfo
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    public void setImageinfo(String imageinfo) {
        this.imageinfo = imageinfo;
    }
}