package com.yangnk.hfn.entity;

import java.io.Serializable;

public class UserTbl implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.id
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.user_name
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.password
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.sex
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tbl.age
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_tbl
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.id
     *
     * @return the value of user_tbl.id
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.id
     *
     * @param id the value for user_tbl.id
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.user_name
     *
     * @return the value of user_tbl.user_name
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.user_name
     *
     * @param userName the value for user_tbl.user_name
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.password
     *
     * @return the value of user_tbl.password
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.password
     *
     * @param password the value for user_tbl.password
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.sex
     *
     * @return the value of user_tbl.sex
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.sex
     *
     * @param sex the value for user_tbl.sex
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tbl.age
     *
     * @return the value of user_tbl.age
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tbl.age
     *
     * @param age the value for user_tbl.age
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    public void setAge(String age) {
        this.age = age;
    }
}