// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dialout.proto

package com.yangnk.grpcapi.dialoutApi;

public final class dialoutProto {
  private dialoutProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dialoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dialoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dialoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dialoutResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rdialout.proto\"I\n\016dialoutRequest\022\021\n\tdev" +
      "iceMsg\030\001 \001(\t\022\022\n\nsensorPath\030\002 \001(\t\022\020\n\010json" +
      "Data\030\003 \001(\t\"\"\n\017dialoutResponse\022\017\n\007message" +
      "\030\001 \001(\t2F\n\016dialoutService\0224\n\rsimpleDialou" +
      "t\022\017.dialoutRequest\032\020.dialoutResponse\"\000B/" +
      "\n\035com.yangnk.grpcapi.dialoutApiB\014dialout" +
      "ProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dialoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dialoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dialoutRequest_descriptor,
        new String[] { "DeviceMsg", "SensorPath", "JsonData", });
    internal_static_dialoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dialoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dialoutResponse_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
