// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dialout.proto

package com.yangnk.grpcapi.dialoutApi;

public interface dialoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dialoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string deviceMsg = 1;</code>
   * @return The deviceMsg.
   */
  String getDeviceMsg();
  /**
   * <code>string deviceMsg = 1;</code>
   * @return The bytes for deviceMsg.
   */
  com.google.protobuf.ByteString
      getDeviceMsgBytes();

  /**
   * <code>string sensorPath = 2;</code>
   * @return The sensorPath.
   */
  String getSensorPath();
  /**
   * <code>string sensorPath = 2;</code>
   * @return The bytes for sensorPath.
   */
  com.google.protobuf.ByteString
      getSensorPathBytes();

  /**
   * <code>string jsonData = 3;</code>
   * @return The jsonData.
   */
  String getJsonData();
  /**
   * <code>string jsonData = 3;</code>
   * @return The bytes for jsonData.
   */
  com.google.protobuf.ByteString
      getJsonDataBytes();
}
