// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dialout.proto

package com.yangnk.grpcapi.dialoutApi;

/**
 * <pre>
 * The request message containing the user's name.
 * </pre>
 *
 * Protobuf type {@code dialoutRequest}
 */
public final class dialoutRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dialoutRequest)
    dialoutRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use dialoutRequest.newBuilder() to construct.
  private dialoutRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private dialoutRequest() {
    deviceMsg_ = "";
    sensorPath_ = "";
    jsonData_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new dialoutRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private dialoutRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            deviceMsg_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            sensorPath_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            jsonData_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dialoutProto.internal_static_dialoutRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dialoutProto.internal_static_dialoutRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dialoutRequest.class, Builder.class);
  }

  public static final int DEVICEMSG_FIELD_NUMBER = 1;
  private volatile Object deviceMsg_;
  /**
   * <code>string deviceMsg = 1;</code>
   * @return The deviceMsg.
   */
  @Override
  public String getDeviceMsg() {
    Object ref = deviceMsg_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      deviceMsg_ = s;
      return s;
    }
  }
  /**
   * <code>string deviceMsg = 1;</code>
   * @return The bytes for deviceMsg.
   */
  @Override
  public com.google.protobuf.ByteString
      getDeviceMsgBytes() {
    Object ref = deviceMsg_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      deviceMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENSORPATH_FIELD_NUMBER = 2;
  private volatile Object sensorPath_;
  /**
   * <code>string sensorPath = 2;</code>
   * @return The sensorPath.
   */
  @Override
  public String getSensorPath() {
    Object ref = sensorPath_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      sensorPath_ = s;
      return s;
    }
  }
  /**
   * <code>string sensorPath = 2;</code>
   * @return The bytes for sensorPath.
   */
  @Override
  public com.google.protobuf.ByteString
      getSensorPathBytes() {
    Object ref = sensorPath_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sensorPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JSONDATA_FIELD_NUMBER = 3;
  private volatile Object jsonData_;
  /**
   * <code>string jsonData = 3;</code>
   * @return The jsonData.
   */
  @Override
  public String getJsonData() {
    Object ref = jsonData_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      jsonData_ = s;
      return s;
    }
  }
  /**
   * <code>string jsonData = 3;</code>
   * @return The bytes for jsonData.
   */
  @Override
  public com.google.protobuf.ByteString
      getJsonDataBytes() {
    Object ref = jsonData_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      jsonData_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDeviceMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceMsg_);
    }
    if (!getSensorPathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sensorPath_);
    }
    if (!getJsonDataBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, jsonData_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDeviceMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceMsg_);
    }
    if (!getSensorPathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sensorPath_);
    }
    if (!getJsonDataBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, jsonData_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dialoutRequest)) {
      return super.equals(obj);
    }
    dialoutRequest other = (dialoutRequest) obj;

    if (!getDeviceMsg()
        .equals(other.getDeviceMsg())) return false;
    if (!getSensorPath()
        .equals(other.getSensorPath())) return false;
    if (!getJsonData()
        .equals(other.getJsonData())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEVICEMSG_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceMsg().hashCode();
    hash = (37 * hash) + SENSORPATH_FIELD_NUMBER;
    hash = (53 * hash) + getSensorPath().hashCode();
    hash = (37 * hash) + JSONDATA_FIELD_NUMBER;
    hash = (53 * hash) + getJsonData().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dialoutRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dialoutRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dialoutRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dialoutRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dialoutRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dialoutRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dialoutRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dialoutRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dialoutRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dialoutRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dialoutRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dialoutRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dialoutRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The request message containing the user's name.
   * </pre>
   *
   * Protobuf type {@code dialoutRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dialoutRequest)
      dialoutRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dialoutProto.internal_static_dialoutRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dialoutProto.internal_static_dialoutRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dialoutRequest.class, Builder.class);
    }

    // Construct using com.yangnk.grpcapi.dialoutApi.dialoutRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      deviceMsg_ = "";

      sensorPath_ = "";

      jsonData_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dialoutProto.internal_static_dialoutRequest_descriptor;
    }

    @Override
    public dialoutRequest getDefaultInstanceForType() {
      return dialoutRequest.getDefaultInstance();
    }

    @Override
    public dialoutRequest build() {
      dialoutRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public dialoutRequest buildPartial() {
      dialoutRequest result = new dialoutRequest(this);
      result.deviceMsg_ = deviceMsg_;
      result.sensorPath_ = sensorPath_;
      result.jsonData_ = jsonData_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dialoutRequest) {
        return mergeFrom((dialoutRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dialoutRequest other) {
      if (other == dialoutRequest.getDefaultInstance()) return this;
      if (!other.getDeviceMsg().isEmpty()) {
        deviceMsg_ = other.deviceMsg_;
        onChanged();
      }
      if (!other.getSensorPath().isEmpty()) {
        sensorPath_ = other.sensorPath_;
        onChanged();
      }
      if (!other.getJsonData().isEmpty()) {
        jsonData_ = other.jsonData_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dialoutRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dialoutRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object deviceMsg_ = "";
    /**
     * <code>string deviceMsg = 1;</code>
     * @return The deviceMsg.
     */
    public String getDeviceMsg() {
      Object ref = deviceMsg_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceMsg_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string deviceMsg = 1;</code>
     * @return The bytes for deviceMsg.
     */
    public com.google.protobuf.ByteString
        getDeviceMsgBytes() {
      Object ref = deviceMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string deviceMsg = 1;</code>
     * @param value The deviceMsg to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceMsg(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceMsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string deviceMsg = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceMsg() {
      
      deviceMsg_ = getDefaultInstance().getDeviceMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string deviceMsg = 1;</code>
     * @param value The bytes for deviceMsg to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceMsg_ = value;
      onChanged();
      return this;
    }

    private Object sensorPath_ = "";
    /**
     * <code>string sensorPath = 2;</code>
     * @return The sensorPath.
     */
    public String getSensorPath() {
      Object ref = sensorPath_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sensorPath_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string sensorPath = 2;</code>
     * @return The bytes for sensorPath.
     */
    public com.google.protobuf.ByteString
        getSensorPathBytes() {
      Object ref = sensorPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sensorPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sensorPath = 2;</code>
     * @param value The sensorPath to set.
     * @return This builder for chaining.
     */
    public Builder setSensorPath(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sensorPath_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sensorPath = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSensorPath() {
      
      sensorPath_ = getDefaultInstance().getSensorPath();
      onChanged();
      return this;
    }
    /**
     * <code>string sensorPath = 2;</code>
     * @param value The bytes for sensorPath to set.
     * @return This builder for chaining.
     */
    public Builder setSensorPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sensorPath_ = value;
      onChanged();
      return this;
    }

    private Object jsonData_ = "";
    /**
     * <code>string jsonData = 3;</code>
     * @return The jsonData.
     */
    public String getJsonData() {
      Object ref = jsonData_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        jsonData_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string jsonData = 3;</code>
     * @return The bytes for jsonData.
     */
    public com.google.protobuf.ByteString
        getJsonDataBytes() {
      Object ref = jsonData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        jsonData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string jsonData = 3;</code>
     * @param value The jsonData to set.
     * @return This builder for chaining.
     */
    public Builder setJsonData(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jsonData_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string jsonData = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearJsonData() {
      
      jsonData_ = getDefaultInstance().getJsonData();
      onChanged();
      return this;
    }
    /**
     * <code>string jsonData = 3;</code>
     * @param value The bytes for jsonData to set.
     * @return This builder for chaining.
     */
    public Builder setJsonDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jsonData_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dialoutRequest)
  }

  // @@protoc_insertion_point(class_scope:dialoutRequest)
  private static final dialoutRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dialoutRequest();
  }

  public static dialoutRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<dialoutRequest>
      PARSER = new com.google.protobuf.AbstractParser<dialoutRequest>() {
    @Override
    public dialoutRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new dialoutRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<dialoutRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<dialoutRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public dialoutRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

