// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dialout.proto

package com.yangnk.grpcapi.dialoutApi;

public interface dialoutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dialoutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
