// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RPCDateService.proto

package com.yangnk.springboottestexample.grpcExample.api;

public final class RPCDateServiceApi {
  private RPCDateServiceApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yangnk_springboottestexample_grpcExample_api_RPCDateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yangnk_springboottestexample_grpcExample_api_RPCDateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yangnk_springboottestexample_grpcExample_api_RPCDateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_yangnk_springboottestexample_grpcExample_api_RPCDateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024RPCDateService.proto\0220com.yangnk.sprin" +
      "gboottestexample.grpcExample.api\"\"\n\016RPCD" +
      "ateRequest\022\020\n\010userName\030\001 \001(\t\"%\n\017RPCDateR" +
      "esponse\022\022\n\nserverDate\030\001 \001(\t2\243\001\n\016RPCDateS" +
      "ervice\022\220\001\n\007getDate\022@.com.yangnk.springbo" +
      "ottestexample.grpcExample.api.RPCDateReq" +
      "uest\032A.com.yangnk.springboottestexample." +
      "grpcExample.api.RPCDateResponse\"\000BG\n0com" +
      ".yangnk.springboottestexample.grpcExampl" +
      "e.apiB\021RPCDateServiceApiP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_yangnk_springboottestexample_grpcExample_api_RPCDateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_yangnk_springboottestexample_grpcExample_api_RPCDateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yangnk_springboottestexample_grpcExample_api_RPCDateRequest_descriptor,
        new String[] { "UserName", });
    internal_static_com_yangnk_springboottestexample_grpcExample_api_RPCDateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_yangnk_springboottestexample_grpcExample_api_RPCDateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_yangnk_springboottestexample_grpcExample_api_RPCDateResponse_descriptor,
        new String[] { "ServerDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
