// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RPCDateService.proto

package com.yangnk.springboottestexample.grpcExample.api;

public interface RPCDateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yangnk.springboottestexample.grpcExample.api.RPCDateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string userName = 1;</code>
   */
  String getUserName();
  /**
   * <code>optional string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
