// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RPCDateService.proto

package com.yangnk.springboottestexample.grpcExample.api;

public interface RPCDateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.yangnk.springboottestexample.grpcExample.api.RPCDateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string serverDate = 1;</code>
   */
  String getServerDate();
  /**
   * <code>optional string serverDate = 1;</code>
   */
  com.google.protobuf.ByteString
      getServerDateBytes();
}
