package com.yangnk.hfn.dao;

import com.yangnk.hfn.entity.Image;
import com.yangnk.hfn.entity.ImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Apr 30 16:26:24 CST 2023
     */
    int countByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Apr 30 16:26:24 CST 2023
     */
    int deleteByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Apr 30 16:26:24 CST 2023
     */
    int insert(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Apr 30 16:26:24 CST 2023
     */
    int insertSelective(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Apr 30 16:26:24 CST 2023
     */
    List<Image> selectByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Apr 30 16:26:24 CST 2023
     */
    int updateByExampleSelective(@Param("record") Image record, @Param("example") ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Apr 30 16:26:24 CST 2023
     */
    int updateByExample(@Param("record") Image record, @Param("example") ImageExample example);

    /**
     * 根据镜像名称查询镜像信息
     * @param imageName
     * @return
     */
    Image selectByName(@Param("imageName") String imageName);
}