package com.yangnk.hfn.dao;

import com.yangnk.hfn.entity.TImage;
import com.yangnk.hfn.entity.TImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    int countByExample(TImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    int deleteByExample(TImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    int insert(TImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    int insertSelective(TImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    List<TImage> selectByExample(TImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    int updateByExampleSelective(@Param("record") TImage record, @Param("example") TImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbggenerated Sun Apr 30 16:22:56 CST 2023
     */
    int updateByExample(@Param("record") TImage record, @Param("example") TImageExample example);
}