package com.yangnk.hfn.dao;

import com.yangnk.hfn.entity.UserTbl;
import com.yangnk.hfn.entity.UserTblExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    int countByExample(UserTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    int deleteByExample(UserTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    int insert(UserTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    int insertSelective(UserTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    List<UserTbl> selectByExample(UserTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    int updateByExampleSelective(@Param("record") UserTbl record, @Param("example") UserTblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tbl
     *
     * @mbggenerated Fri Jul 15 15:22:31 CST 2022
     */
    int updateByExample(@Param("record") UserTbl record, @Param("example") UserTblExample example);

    List<UserTbl> selectByUserName(@Param(("userName")) String userName);
}