package com.yangnk.redisDemo.entity;


import java.io.Serializable;

public class Network implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column network.id
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column network.network
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    private String network;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table network
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column network.id
     *
     * @return the value of network.id
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column network.id
     *
     * @param id the value for network.id
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column network.network
     *
     * @return the value of network.network
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    public String getNetwork() {
        return network;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column network.network
     *
     * @param network the value for network.network
     *
     * @mbggenerated Tue Jun 07 10:09:49 CST 2022
     */
    public void setNetwork(String network) {
        this.network = network;
    }

    @Override
    public String toString() {
        return "Network{" + "id=" + id + ", network='" + network + '\'' + '}';
    }
}